name: backend_v2
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.3

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

  # api stuff
  alfred: ^1.1.1

  # database stuff
  sembast: ^3.7.1+3

  # random id
  uuid:

  # json web token
  dart_jsonwebtoken: ^2.14.0

  # encryption
  crypto:
  aescryptojs:

  # scheduler
  cron:

  # env
  dotenv:

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
